---
author: "Abbie Benfield"
date: '2022-04-17'
output: html_document
---

Abbie
- ~~PCR - L10~~
- ~~PLS - L11~~
- Smoothing Splines - L13
- GAM - L13
- Classification Trees - L14
- SVM - L15

```{r, message = FALSE}
library(tidyverse)
library(janitor)
library(performance)
```


```{r, message = FALSE}
spotify <- read_csv("spotify_dataset.csv") %>%
  clean_names() %>%
  na.omit() %>% # 11 NAs omitted
  mutate(top_20 = ifelse(highest_charting_position <= 20, TRUE, FALSE))

sp <- spotify %>%
  select(-index, -song_name, -artist, -song_id, -weeks_charted, -highest_charting_position, -week_of_highest_charting, -genre, -release_date, -chord)

set.seed(1)

train <- sp %>% 
  sample_frac(0.5)

test <- sp %>% 
  setdiff(train)

x_train <- model.matrix(top_20 ~ ., train)[, -1]
x_test <- model.matrix(top_20 ~ ., test)[, -1]

y_train <- train %>%
  select(top_20) %>%
  unlist() %>%
  as.numeric()

y_test <- test %>%
  select(top_20) %>%
  unlist() %>%
  as.numeric()
```

```{r}
# PCR
library(pls)

set.seed(1)
pcr_train <- pcr(top_20 ~ ., data = train, scale = TRUE, validation = "CV")
summary(pcr_train)
validationplot(pcr_train, val.type = "MSEP")

pcr_preds <- predict(pcr_train, x_test, ncomp = 10)
mean((pcr_preds - y_test)^2)

pcr_full <- pcr(top_20 ~ ., data = sp, scale = TRUE, ncomp = 10)
summary(pcr_full)
```

```{r}
# PLS
set.seed(1)
pls_train <- plsr(top_20 ~ ., data = train, scale = TRUE, validation = "CV")
summary(pls_train)
validationplot(pls_train, val.type = "MSEP")

pls_preds <- predict(pls_train, x_test, ncomp = 4)
mean((pls_preds - y_test)^2)

pls_full <- plsr(top_20 ~ ., data = sp, scale = TRUE, ncomp = 4)
summary(pls_full)
```

