---
title: "Final Project Report"
author: "Abbie Benfield, Annah Mutaya"
date: "5/6/2022"
output:
  html_document: default
---

# Introduction

```{r, message = FALSE}
library(tidyverse)
library(janitor)
library(skimr)
library(corrplot)
library(gbm)
library(e1071)
library(class)

spotify_full <- read_csv("spotify_dataset.csv") %>%
  clean_names() %>%
  mutate(top_20 = ifelse(highest_charting_position <= 20, TRUE, FALSE))

head(spotify_full)
```

# Exploratory Data Analysis

```{r}
skim(spotify_full)
```

```{r}
ggplot(spotify_full, aes(x = highest_charting_position)) +
  geom_freqpoly(bins = 30) +
  labs(x = "Highest Charting Postion", y = "Count", title = "Distribution of Highest Charting Position")
```


```{r}
clean <- spotify_full %>%
  na.omit() %>%
  select(
    -index, -song_id, -weeks_charted, -week_of_highest_charting, -genre,
    -release_date, -chord, -song_name, -artist, -highest_charting_position
  )

skim(clean)
```


```{r}
corrplot(cor(clean), method = "circle", tl.col = "black", tl.srt = 45, type = "upper")
```


# Methodology

```{r}
set.seed(1)

test <- clean %>%
  sample_n(1000)

train <- clean %>%
  setdiff(test)

scaled_test <- test %>%
  select(-top_20) %>%
  scale() %>%
  data.frame()

test_20 <- test %>%
  select(top_20) %>%
  .$top_20

scaled_train <- train %>%
  select(-top_20) %>%
  scale() %>%
  data.frame()

train_20 <- train %>%
  select(top_20) %>%
  .$top_20
```

### Logistic

```{r}
glm_fit <- glm(top_20 ~ .,
  data = train,
  family = binomial
)

glm_probs <- data.frame(probs = predict(glm_fit,
  newdata = test,
  type = "response"
))

glm_pred <- glm_probs %>%
  mutate(pred = ifelse(probs > .5, TRUE, FALSE))

glm_pred <- cbind(test, glm_pred)

glm_pred %>%
  count(pred, top_20) %>%
  spread(top_20, n, fill = 0)

glm_pred %>%
  summarize(
    score = mean(pred == top_20),
    recip = mean(pred != top_20)
  )
```


### KNN

```{r}
val <- 0
kmax <- 1

for (k in 1:20) {
  set.seed(1)
  knn_pred <- knn(scaled_train, scaled_test, train_20, k)
  tab <- table(knn_pred, test_20)
  if ((tab[2, 2] / (tab[2, 2] + tab[1, 2])) > val) {
    val <- (tab[2, 2] / (tab[2, 2] + tab[1, 2]))
    kmax <- k
  }
}

val
kmax


knn_preds <- knn(scaled_train, scaled_test, train_20, kmax)
table(knn_preds, test_20)
```

### Trees

```{r}
# Boosting
set.seed(1)
boost <- gbm(top_20 ~., data = train, distribution = "bernoulli", n.trees = 1000, shrinkage = .01)

summary(boost)

probs <- predict(boost, newdata = test, n.trees = 1000, type = "response")
preds <- ifelse(probs > .2, 1, 0)
table(test$top_20, preds)
```

### SVM?

```{r}


```