---
title: "Outline"
author: "Abbie Benfield, Annah Mutaya"
date: '2022-04-17'
output: html_document
---

Dataset: [Spotify Top 200 Charts (2020-2021)](https://www.kaggle.com/datasets/sashankpillai/spotify-top-200-charts-20202021)
Problem: What makes a top 20 song?

1. Exploratory Data Analysis - started
  
2. Making Models 
  <!-- - Multiple Linear Regression - started  -->
  - Multiple Logistic Regression - started
  - KNN - started
  - Best Subset - started
  <!-- - Ridge -->
  <!-- - Lasso -->
  <!-- - PCR - started -->
  <!-- - PLS - started -->
  <!-- - Smoothing Splines -->
  <!-- - GAM -->
  - Classification Trees
  - SVM
  
3. Select final model and write-up findings

4. Write-up complete report

Questions: 
1. Are we trying the right types of models/are we trying too many?
2. How much much EDA should we perform?
3. We haven't talked about variable selection in all methods - how should we address it in methods such as PCR?


Notes from Checkpoint meeting:
- only logisitic, knn, classification trees, svm for classification
- PCA for EDA (probably enough unless there's something special) -> consider doing clustering instead
- Best Subset Selection for choosing predictors (not EDA)
- no exact min/max on page count
- don't have to do all 4 model types (logistic and svm may have significant similarities)
- by friday of finals at 2pm (earlier the better)
